server:
  port: 8088

#  org.springframework ? ??? ??? ?? ?????? ??
logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages # 우리가 사용할 다국어파일(message파일)의 이름을 messages라고 하겠다. Resources에 저장하면됨